{{- if not .Values.secrets.pkiCert.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-pki-cert
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
type: Opaque
data:
  intermediate-ca.crt: {{ required "You must specify the Intermediate PKI Cert as Base64 value" .Values.secrets.pkiCert.intermediate }}
  root-ca.crt: {{ required "You must specify the Root PKI Cert as Base64 value" .Values.secrets.pkiCert.root }}
---
{{- end }}

{{- if not .Values.secrets.pkiKey.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-pki-key
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
type: Opaque
data:
  intermediate-ca.key: {{ required "You must specify the Intermediate PKI Key as Base64 value" .Values.secrets.pkiKey.intermediate }}
---
{{- end }}

{{- if not .Values.secrets.signingApiSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-signing-api-secret
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  api-secret: {{ (.Values.secrets.signingApiSecret.api_secret | default (randAlphaNum 64)) | b64enc }}
---
{{- end }}

{{- if not .Values.secrets.ctApiSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-ct-api-secret
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  api-secret: {{ (.Values.secrets.ctApiSecret.api_secret | default (randAlphaNum 64)) | b64enc }}
---
{{- end }}

{{- if not .Values.secrets.oidcClientSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-oidc-client-secret
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  client-secret: {{ (.Values.secrets.oidcClientSecret.api_secret | default "Super-+Secret_=Key0123456789") | b64enc }}
---
{{- end }}

{{- if not .Values.secrets.flaskSecretKey.frontend.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-flask-secret-key-frontend
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  {{ .Values.secrets.flaskSecretKey.frontend.key | default "flask-secret-key" }}: {{ (.Values.secrets.flaskSecretKey.frontend.value | default (randAlphaNum 64)) | b64enc }}
---
{{- end }}

{{- if not .Values.secrets.flaskSecretKey.signing.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-flask-secret-key-signing
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  {{ .Values.secrets.flaskSecretKey.signing.key | default "flask-secret-key" }}: {{ (.Values.secrets.flaskSecretKey.signing.value | default (randAlphaNum 64)) | b64enc }}
---
{{- end }}

{{- if not .Values.secrets.flaskSecretKey.certtransparency.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-flask-secret-key-certtransparency
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  {{ .Values.secrets.flaskSecretKey.certtransparency.key | default "flask-secret-key" }}: {{ (.Values.secrets.flaskSecretKey.certtransparency.value | default (randAlphaNum 64)) | b64enc }}
---
{{- end }}

{{- if not .Values.secrets.fernet.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-fernet
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  {{ .Values.secrets.fernet.key | default "fernet-key" }}: {{ (.Values.secrets.fernet.value | default "YenxIAHqvrO7OHbNXvzAxEhthHCaitvnV9CALkQvvCc=") | b64enc }}
---
{{- end }}

{{- if not .Values.secrets.caKeyPassphrase.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-ca-key-passphrase
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  passphrase: {{ .Values.secrets.caKeyPassphrase.value | b64enc }}
---
{{- end }}

{{- if or .Values.certtransparency.enabled (and .Values.frontend.enabled .Values.frontend.adminService.enabled) (and .Values.frontend.enabled .Values.frontend.userService.enabled) (and .Values.frontend.enabled .Values.frontend.combinedService.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-manager.fullname" . }}-db-users
  labels:
    {{- include "openvpn-manager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
{{- if .Values.frontend.config.database.password }}
  frontend-password: {{ .Values.frontend.config.database.password | b64enc }}
  frontend-uri: {{ include "openvpn-manager.databaseUriWithPassword" (dict "config" .Values.frontend.config "password" .Values.frontend.config.database.password) | b64enc }}
{{- end }}
{{- if .Values.certtransparency.config.database.password }}
  certtransparency-password: {{ .Values.certtransparency.config.database.password | b64enc }}
  certtransparency-uri: {{ include "openvpn-manager.databaseUriWithPassword" (dict "config" .Values.certtransparency.config "password" .Values.certtransparency.config.database.password) | b64enc }}
{{- end }}
{{- end }}
